# Build & Test
# Versions: .NET Framework
# Trigger: pull_request, push
# actions/checkout@v2 and actions/setup-dotnet@v1 are community actions that will get your code and setup dotnet

name: Build .NET Framework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
         
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1   

    - name: Build SimTuning.WPF.App
      run: msbuild ./src/SimTuning.WPF.App/SimTuning.WPF.App.csproj /restore /p:Configuration=Release
