# Build & Test
# Versions: Xamarin.Forms
# Trigger: pull request, push
# https://docs.github.com/en/actions/guides/building-and-testing-net

name: Build Xamarin.Forms

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1     
      
    - name: Build SimTuning.Forms.Droid
      run: msbuild ./src/SimTuning.Forms.Droid/SimTuning.Forms.Droid.csproj /restore /p:Configuration=Release

    - name: Build SimTuning.Forms.iOS
      run: msbuild ./src/SimTuning.Forms.iOS/SimTuning.Forms.iOS.csproj /restore /p:Configuration=Release
